config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"
  resources :books
  resources :fruits
  namespace :api do
    resources :fruits, only: %i(destroy) do
      resource :position, only: %i(update), controller: "fruits/position"
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
end

app/models/fruit.rb
# frozen_string_literal: true

class Fruit < ApplicationRecord
  acts_as_list
end

app/controllers/api/fruits/position_controller.rb
# frozen_string_literal: true

class Api::Fruits::PositionController < ApplicationController
  wrap_parameters :category

  def update
    @fruit = Fruit.find(params[:fruit_id])
    if @fruit.update(fruit_params)
      head :no_content
    else
      head :bad_request
    end
  end

  private
    def fruit_params
      params.require(:category).permit(:position)
    end
end

app/controllers/api/fruits_controller.rb
# frozen_string_literal: true

class Api::FruitsController < ApplicationController
  def destroy
    @fruit = Fruit.find(params[:id])
    if @fruit.destroy
      head :no_content
    else
      head :bad_request
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description)
    end
end

app/controllers/fruits_controller.rb
# frozen_string_literal: true

class FruitsController < ApplicationController
  before_action :set_fruit, only: [:show, :edit, :update, :destroy]

  # GET /fruits
  # GET /fruits.json
  def index
    @fruits = Fruit.all.order("position")
  end

  # GET /fruits/1
  # GET /fruits/1.json
  def show
  end

  # GET /fruits/new
  def new
    @fruit = Fruit.new
  end

  # GET /fruits/1/edit
  def edit
  end

  # POST /fruits
  # POST /fruits.json
  def create
    @fruit = Fruit.new(fruit_params)

    respond_to do |format|
      if @fruit.save
        format.html { redirect_to @fruit, notice: "Fruit was successfully created." }
        format.json { render :show, status: :created, location: @fruit }
      else
        format.html { render :new }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fruits/1
  # PATCH/PUT /fruits/1.json
  def update
    respond_to do |format|
      if @fruit.update(fruit_params)
        format.html { redirect_to @fruit, notice: "Fruit was successfully updated." }
        format.json { render :show, status: :ok, location: @fruit }
      else
        format.html { render :edit }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fruits/1
  # DELETE /fruits/1.json
  def destroy
    @fruit.destroy
    respond_to do |format|
      format.html { redirect_to fruits_url, notice: "Fruit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fruit
      @fruit = Fruit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fruit_params
      params.require(:fruit).permit(:name, :description, :position)
    end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/helpers/fruits_helper.rb
# frozen_string_literal: true

module FruitsHelper
end

app/views/books/_form.html.slim
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      h2 = "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      ul
        - @book.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/books/edit.html.slim
h1 Editing book

== render 'form'

=> link_to 'Show', @book
'|
=< link_to 'Back', books_path

app/views/books/index.html.slim
h1 Listing books

table
  thead
    tr
      th Title
      th Description
      th
      th
      th

  tbody
    - @books.each do |book|
      tr
        td = book.title
        td = book.description
        td = link_to 'Show', book, class: "button is-light"
        td = link_to 'Edit', edit_book_path(book), class: "button is-light"
        td = link_to 'Destroy', book, data: { confirm: 'Are you sure?' }, method: :delete, class: "button is-text"

br

= link_to 'New Book', new_book_path, class: "button is-primary is-light"

app/views/books/new.html.slim
h1 New book

== render 'form'

= link_to 'Back', books_path

app/views/books/show.html.slim
p#notice = notice

p
  strong Title:
  = @book.title
p
  strong Description:
  = @book.description

=> link_to 'Edit', edit_book_path(@book)
'|
=< link_to 'Back', books_path

app/views/fruits/_form.html.slim
= form_for @fruit do |f|
  - if @fruit.errors.any?
    #error_explanation
      h2 = "#{pluralize(@fruit.errors.count, "error")} prohibited this fruit from being saved:"
      ul
        - @fruit.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/fruits/edit.html.slim
h1 Editing fruit

== render 'form'

=> link_to 'Show', @fruit
'|
=< link_to 'Back', fruits_path

app/views/fruits/index.html.slim
h1 Listing fruits
#js-index(data-fruits="#{@fruits.to_json}")
table
  thead
    tr
      th Name
      th Description
      th
      th
      th

  tbody
    - @fruits.each do |fruit|
      tr
        td = fruit.name
        td = fruit.description
        td = link_to 'Show', fruit
        td = link_to 'Edit', edit_fruit_path(fruit)
        td = link_to 'Destroy', fruit, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Fruit', new_fruit_path

app/views/fruits/new.html.slim
h1 New fruit

== render 'form'

= link_to 'Back', fruits_path

app/views/fruits/show.html.slim
p#notice = notice

p
  strong Name:
  = @fruit.name
p
  strong Description:
  = @fruit.description

=> link_to 'Edit', edit_fruit_path(@fruit)
'|
=< link_to 'Back', fruits_path

app/views/home/index.html.slim
h1.title Home#index
p
  | ホーム

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RailsVueProject
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    section.hero.is-primary.is-medium
      .hero-head
        nav.navbar
          .container
            .navbar-brand
              = link_to root_path, class: 'navbar-item'
                .title
                  | RailsVueProject
            #navbarMenuHeroA.navbar-menu
              .navbar-end
                = link_to books_path, class: 'navbar-item'
                  | Books
                = link_to fruits_path, class: 'navbar-item'
                  | Fruits
    = yield